### ISSUE TITLE
Docs Failed to build

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#348]
Updated the docs in https://github.com/IBM/nodejs-itoolkit/pull/346

Then it failed to build with:

```
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/sphinx/__main__.py", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 18, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 24, in <module>
    from sphinx.config import Config
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 16, in <module>
    from sphinx.util.tags import Tags
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/sphinx/util/tags.py", line 3, in <module>
    from jinja2 import nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/latest/lib/python3.7/site-packages/markupsafe/__init__.py)
```

**Comment by abmusse** [comment]
Related:

https://github.com/mozilla/sphinx-js/issues/190
